### ISSUE TITLE
An error in the uses in the ReadMe.

### ISSUE THREAD

**Issue by takafumi-suzuki-cresco** [bthomas2622/copilot-metrics-export-action#2]
Hello.
I was able to use it right away.
One comment.

There is a discrepancy between "uses" in ReadMe and "uses" in Marketplace.
ReadMe : bthomas2622/copilot-usage-metrics-api-export@v1
Marketplace : bthomas2622/copilot-metrics-export-action@v1

Marketplace seems to be correct.
I suggest correcting the ReadMe.

**Comment by bthomas2622** [comment]
fixed thank you so much!
