### ISSUE TITLE
API Copilot Endpoint for Teams Not Available, Resulting in 404 Error

### ISSUE THREAD

**Issue by alexeyvoren** [bthomas2622/copilot-metrics-export-action#3]
It appears that GitHub does not currently provide an API Copilot endpoint for teams. This has resulted in a job failure due to a 404 (Not Found) error when team parameters are enabled.

```
team-summary: true
team-name: someTeam
```

**Comment by alexeyvoren** [comment]
In continuation of this topic, I would like to suggest that it would be highly beneficial to implement usage statistics for Copilot across all users within a team/organization/enterprise.

Currently, there is an endpoint available for individual users within an organization:

```
curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer xxxxx" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/orgs/ORG/members/USER/copilot

**Comment by bthomas2622** [comment]
Hi @alexeyvoren this was due to GitHub temporarily removing the Teams endpoint from the official API during the beta period, it has been restored now
